<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE thresholds [
  <!ELEMENT thresholds (threshold)+>
  <!ATTLIST thresholds xmlns CDATA #FIXED ''>
  <!ELEMENT threshold (description,levels)>
  <!ATTLIST threshold xmlns CDATA #FIXED '' alias NMTOKEN #IMPLIED
    map NMTOKEN #REQUIRED>
  <!ELEMENT description (#PCDATA)>
  <!ATTLIST description xmlns CDATA #FIXED ''>
  <!ELEMENT levels (#PCDATA)>
  <!ATTLIST levels xmlns CDATA #FIXED '' divisor CDATA #REQUIRED
    height CDATA #REQUIRED width CDATA #REQUIRED>
]>
<thresholds>
	<threshold map="bn16x16">
		<description>Bluenoise dither map 16x16</description>
		<levels width="16" height="16" divisor="256">
			 184 103 170 210 150 224 169 244  95 160 219 136 196  69 213 241
			 132  55   2  51  92  68 114  39 185  57 126  53  99   5 155  41
			 225 198 118 239 192  14 207 135   1 238 201 165 249 180 111  82
			 158  26 147  74 172  37 250  78 151  24  88  15  72  35 235  20
			 178 251 100 216 127 157  97 176 218 108 191 120 221 142 203  89
			 116  63   8  46 141  59 202  50  21  66 233  44 159  61  10  47
			 133 212 188 240 107 229   6 121 243 144 171 130 209 102 194 230
			 167  31 153  84 177  27 168  85 187  33  94  79 254  29 146  75
			 246  96  19 123 208  70 252 104 206  13 227 174   4 124 182 109
			 199  58 223  54 148  16 139  42 154  56 112  52 200  67 234  40
			 128   0 183 242  90 193 226  73 215 181 245 137 163  91  18 156
			 173  23 106  71 166  36 110   3 125  25  22  77 211  38 220  81
			 237 204 138 217 131 247 179  87 236 162  98 228   7 186 140 115
			  93  65 161  43   9  62 152  48 205  64 189  45 105  60 248  49
			  11 222 122 190 101 232 195 117 143  12 253 149 175 129 164 197
			 145  34 255  80 134  30  17  76 214  32 113  83 231  28 119  86
		</levels>
	</threshold>
	<threshold map="bni16x16">
		<description>Bluenoise dither map inverse 16x16</description>
		<levels width="16" height="16" divisor="256">
			  71 152  85  45 105  31  86  11 160  95  36 119  59 186  42  14
			 123 200 253 204 163 187 141 216  70 198 129 202 156 250 100 214
			  30  57 137  16  63 241  48 120 254  17  54  90   6  75 144 173
			  97 229 108 181  83 218   5 177 104 231 167 240 183 220  20 235
			  77   4 155  39 128  98 158  79  37 147  64 135  34 113  52 166
			 139 192 247 209 114 196  53 205 234 189  22 211  96 194 245 208
			 122  43  67  15 148  26 249 134  12 111  84 125  46 153  61  25
			  88 224 102 171  78 228  87 170  68 222 161 176   1 226 109 180
			   9 159 236 132  47 185   3 151  49 242  28  81 251 131  73 146
			  56 197  32 201 107 239 116 213 101 199 143 203  55 188  21 215
			 127 255  72  13 165  62  29 182  40  74  10 118  92 164 237  99
			  82 232 149 184  89 219 145 252 130 230 233 178  44 217  35 174
			  18  51 117  38 124   8  76 168  19  93 157  27 248  69 115 140
			 162 190  94 212 246 193 103 207  50 191  66 210 150 195   7 206
			 244  33 133  65 154  23  60 138 112 243   2 106  80 126  91  58
			 110 221   0 175 121 225 238 179  41 223 142 172  24 227 136 169
		</levels>
	</threshold>
	<threshold map="bn32x32">
		<description>Bluenoise dither map 32x32</description>
		<levels width="32" height="32" divisor="256">
			 147  42 133 102  79  44 136  85 202  40 165 124 193 236  84   3  67 186  40 239 133 176  81 121 183  69 196  84 251 154 227  66
			 244 211  15 185 250 114 208  56 149 254  76  23  58 156  45 197 252  98 166 118 226  52 148 245  46  15 168  39 118 200 106 177
			 119  59  92  27 140 173  12 230 111   2 179 233 205  93 226 145 126  57  22 195  73 104 214 130  88 233 139 221  11  52  80  19
			 166 191 230 157 218  69  96  33 189  62  99  24 137  12 113  33 173 215  87  26   2 162 190  33 112 203  61  99 163 184 217  33
			 143 104  73   1  51 126 245 161 211 131 222 168  73 182 210  79   8 242 156 204 250 127  66 229 146 170  24  24 243 124  92 236
			  46  21 247 116 200 178 143  77  17  50 150 109 249  48 153 229 100  51 139 110  46  90 180  11  49 253  82 189 148  67   6 205
			  64 196 169  32  83 214  43 114 176 239  86   6 190  23  62 122 191  19  75 175 224 150 209 108  74 197   2 114 224  42 135 161
			 229  86 127 222 135 100   7 228  31 196  64 216  35  97 238 171  29 207 232 129  63  18  30 238 132 155  37 211  96 180 249 101
			 184   7  53 152  65 243 188 150  94 126 137 159 117 204 146   0  89 158 103  39 198 116 168  86 177 227  65 138 163  76  16  29
			 146 109 251 199 172 120  50  72 170 246  47 226 179  77  47 222  68 247 141 183 241  73 213  10  51 103  14 245  44 198 117 218
			  78  40  20  94  26  14 225 141 212   4 105  69  13 254 133 193 119  17  54  82   3 147  40 250 123 208 187  82 129 231  57 157
			 238 203 164 215 138  85 194 112  34  82 206 151  26 113  91 156  37 213 170 224 109 166  93 183  71 158  27 143 170 102   1 188
			 125  55 112  70 242 174  60 252  23 187 121 240 171 196 220  62 182  96 136  25 190  57 234 140  22 221  96 241  60 210  34  90
			 177   9 235 154  42   0  94 153  49 165  58  19  81  42   6 144 248  14  71 242  21 119 206  35 110  55   5 200 120  21 254 138
			 223  31  89 192 127 207 229 116 201 237  99 217 142 123 234 104  49 202 159 102 215  80   7 171 192 231 162  76 181  45 153  72
			 165 201 120  17  79 167  29 144  76   5  34 184  65 204 167  75 219 123  36 176 145  43 253  89  65 143  38 108 233  88 195 107
			  20  64 228  39 240 108  63 187 131 221 110 155 251  95  31 136 180   1  91 237  59 194 158 122 213  12 247 131 169  10 216  53
			 249  98 149 181 131 213 127 249  47  85 176  23  50   8 193 111 243  51 199 134  13 104 130  28 168  95  55 205  67  25 146 124
			  38 208  11  77  54 172  90 160 203 147 231  71 211 148 228  62 161  81 151 227  70 206 241  77 225 195 118 153 222 103 236 173
			  86 160 115 192 246 141  37 118  66   9  24 123 186 102  38 128 206 126  27  98 165  41 180 147  16  44 178  85   0 185  75  18
			 231  60 220  28 103   2 230 188 216 107 239 163  83 247 142 178  92 253 186 130 219   3  87 115  61 234 132  35 252 120  48 195
			 106   7 134 167 202  68 152  43  19  89 179 135  54  15  69 219  48  10  67 233 111  56 204 248 163  98 207 149  63 162 212 140
			 172 244  49  83 235  22  97 171 254  56 209  36 226 194 119 157 107 170 141  38 157 188 139  31   9 191  74  13 220  91 129  32
			  71  97 144 184 122  52 216 137  81 155 116   0 151  90 242  30 197 238  83 210  97  18  78 224 124  50 240 112 186  52 232 192
			  13 201 220  37 161 241 189  30 128 202 237 101  60 182  10  78 130  53   5 177 245  47 208 166  94 178 145  27 167  18 114 152
			 253  58 107   4  91  70  11 101 175  46  72 164 217  41 140 210 154 223 113  63 132 150 110  61 255 129  80 225 100 239  80  41
			 122 164 133 227 199 148 117 212 244 142 128 185 125 252 105 174  36  88  22 203  25 232   1 194  35 214   8 198  64 137 207 179
			 218  79  25 175  54 250  39 160  56  93 232  26  87  16  68 234 121 189 248 160 101 183  85 138 156 105  53 149 181  34   4  95
			 144 191 236 125  84  17 182  78   3 197 113 209 151 190  45 158   6  75  43 134  68 219  41 237  72 174 243  20 111 246 159  59
			  45  14 105 169 142 214 100 223 135 173  48   9  74 223 132 201  93 228 175 212  16 115 172  21 125 200  88  44 218  74 128 230
			 115 248  70  36 193  61 121  30 240  66 145 246 169 108  59 244  28 139 109  55 155 251  95  57 225  28 136 164 187  99 205 174
			  87 199 159 221   4 235 162 185  15 106 215  92  32  20 181 117 154 217  12  84 198  32   5 209 152 106 235   0  58 134  29   8
		</levels>
	</threshold>
	<threshold map="bni32x32">
		<description>Bluenoise dither map inverse 32x32</description>
		<levels width="32" height="32" divisor="256">
			 108 213 122 153 176 211 119 170  53 215  90 131  62  19 171 252 188  69 215  16 122  79 174 134  72 186  59 171   4 101  28 189
			  11  44 240  70   5 141  47 199 106   1 179 232 197  99 210  58   3 157  89 137  29 203 107  10 209 240  87 216 137  55 149  78
			 136 196 163 228 115  82 243  25 144 253  76  22  50 162  29 110 129 198 233  60 182 151  41 125 167  22 116  34 244 203 175 236
			  89  64  25  98  37 186 159 222  66 193 156 231 118 243 142 222  82  40 168 229 253  93  65 222 143  52 194 156  92  71  38 222
			 112 151 182 254 204 129  10  94  44 124  33  87 182  73  45 176 247  13  99  51   5 128 189  26 109  85 231 231  12 131 163  19
			 209 234   8 139  55  77 112 178 238 205 105 146   6 207 102  26 155 204 116 145 209 165  75 244 206   2 173  66 107 188 249  50
			 191  59  86 223 172  41 212 141  79  16 169 249  65 232 193 133  64 236 180  80  31 105  46 147 181  58 253 141  31 213 120  94
			  26 169 128  33 120 155 248  27 224  59 191  39 220 158  17  84 226  48  23 126 192 237 225  17 123 100 218  44 159  75   6 154
			  71 248 202 103 190  12  67 105 161 129 118  96 138  51 109 255 166  97 152 216  57 139  87 169  78  28 190 117  92 179 239 226
			 109 146   4  56  83 135 205 183  85   9 208  29  76 178 208  33 187   8 114  72  14 182  42 245 204 152 241  10 211  57 138  37
			 177 215 235 161 229 241  30 114  43 251 150 186 242   1 122  62 136 238 201 173 252 108 215   5 132  47  68 173 126  24 198  98
			  17  52  91  40 117 170  61 143 221 173  49 104 229 142 164  99 218  42  85  31 146  89 162  72 184  97 228 112  85 153 254  67
			 130 200 143 185  13  81 195   3 232  68 134  15  84  59  35 193  73 159 119 230  65 198  21 115 233  34 159  14 195  45 221 165
			  78 246  20 101 213 255 161 102 206  90 197 236 174 213 249 111   7 241 184  13 234 136  49 220 145 200 250  55 135 234   1 117
			  32 224 166  63 128  48  26 139  54  18 156  38 113 132  21 151 206  53  96 153  40 175 248  84  63  24  93 179  74 210 102 183
			  90  54 135 238 176  88 226 111 179 250 221  71 190  51  88 180  36 132 219  79 110 212   2 166 190 112 217 147  22 167  60 148
			 235 191  27 216  15 147 192  68 124  34 145 100   4 160 224 119  75 254 164  18 196  61  97 133  42 243   8 124  86 245  39 202
			   6 157 106  74 124  42 128   6 208 170  79 232 205 247  62 144  12 204  56 121 242 151 125 227  87 160 200  50 188 230 109 131
			 217  47 244 178 201  83 165  95  52 108  24 184  44 107  27 193  94 174 104  28 185  49  14 178  30  60 137 102  33 152  19  82
			 169  95 140  63   9 114 218 137 189 246 231 132  69 153 217 127  49 129 228 157  90 214  75 108 239 211  77 170 255  70 180 237
			  24 195  35 227 152 253  25  67  39 148  16  92 172   8 113  77 163   2  69 125  36 252 168 140 194  21 123 220   3 135 207  60
			 149 248 121  88  53 187 103 212 236 166  76 120 201 240 186  36 207 245 188  22 144 199  51   7  92 157  48 106 192  93  43 115
			  83  11 206 172  20 233 158  84   1 199  46 219  29  61 136  98 148  85 114 217  98  67 116 224 246  64 181 242  35 164 126 223
			 184 158 111  71 133 203  39 118 174 100 139 255 104 165  13 225  58  17 172  45 158 237 177  31 131 205  15 143  69 203  23  63
			 242  54  35 218  94  14  66 225 127  53  18 154 195  73 245 177 125 202 250  78  10 208  47  89 161  77 110 228  88 237 141 103
			   2 197 148 251 164 185 244 154  80 209 183  91  38 214 115  45 101  32 142 192 123 105 145 194   0 126 175  30 155  16 175 214
			 133  91 122  28  56 107 138  43  11 113 127  70 130   3 150  81 219 167 233  52 230  23 254  61 220  41 247  57 191 118  48  76
			  37 176 230  80 201   5 216  95 199 162  23 229 168 239 187  21 134  66   7  95 154  72 170 117  99 150 202 106  74 221 251 160
			 111  64  19 130 171 238  73 177 252  58 142  46 104  65 210  97 249 180 212 121 187  36 214  18 183  81  12 235 144   9  96 196
			 210 241 150  86 113  41 155  32 120  82 207 246 181  32 123  54 162  27  80  43 239 140  83 234 130  55 167 211  37 181 127  25
			 140   7 185 219  62 194 134 225  15 189 110   9  86 147 196  11 227 116 146 200 100   4 160 198  30 227 119  91  68 156  50  81
			 168  56  96  34 251  20  93  70 240 149  40 163 223 235  74 138 101  38 243 171  57 223 250  46 103 149  20 255 197 121 226 247
		</levels>
	</threshold>
	<threshold map="bn64x64">
		<description>Bluenoise dither map 64x64</description>
		<levels width="64" height="64" divisor="256">
			 187  80 245   1 181  89 137  45   5 167 222 183  59 116 155  12 210  46 224 136 235  19 146 227  91 175   2 110 239  43   7  63 251 161  73 236 143  90 255  70 127  31  78 115  61  23 138 104 253 199   9 234 136  46   4 118  84 168 190  62  13 183 235 100
			 141  30 194 125  71 156 188 230 127  56 101 137 209  91 191  65 173 116 159  29  92 167  39  71  21 123 231  55 137 215  91 186  23 109 217 171  62 127 216 101 199 132 236 208 172  44 186  68 145  40 111 178  94 158  74 213 153 234  44 219 142  37  70   7
			 209 106 227 146  49 254 111  69 153 192 250  31 161 231  42 106 254  79 201 128 214 112 251 184 217  30 199 161  72 177 117 228  46  87  10  31 188 152  46 171 225  56 150  92 125 240 212  12 224 167  71 209  55 240 185  24  20  68 109 129 204  95 252 175
			  18  66 169  91 130 199  27  21 213  80 116   1  70 125  22 207 146   3  55 185  64   7  84 132 156 104  82  23 249  11  24 157 143 207 126 243 104 205   0 119  81  15 186  36   4  76 110  27  94 127 244  16 147 124 103 230 141 176 248  78 167 123 151  45
			 134 244  38 215 121 163 223  97 172  41 147 201 176 243  87 163  33  96 226 135 240 178  47 201  58 243 148 186  49  98 204  75 246  55 166  79 136  64 232  26 160 246 103 230 163 142 175 196 150  48 187  85  34 203  10  86  47 211   0  32 192  54 213  82
			 196 155 113 181  57  81   6  52 238  17 224  94  47  13  57 185 238 119 171  39 100 157  20 232 119   8  37 214 120 230 131 174 103   4 196  38 218 177  95 141 193  47 129  69 199  51 247  67 229 131 218 111 175 246  66 163 197 117  90 157 232  12 113 227
			  96   4  73 228 141 247 194 159 109 184  64 129 213 111 222 134  68 214  18  75 143 220  26  95 189  72 172  89 143  60 191  40 123 223  91 149 121  14 250  57 211 112 178 216  96  20 121   7 103 163  60   2 152  45 136 224  23  61 239 134  99  65 173  26
			 186  47 203  21  32 105 130  71 139  33 248 163 190  27 155  82  10  48 189 248 112 202  69 168 140 218 113 241   3 164  83 236  23  64 170 239  50  85 164 126   7  84 152  31 139 221  40  83 206  32 251  77 210  95 181 107  36 189 169  44 219 147 241 130
			 162 252  87 153 173 211  45 235 199   8  91 142  75 126 251 172 205 145  94 160  54   1 124 251  42  21  55 192  31 211 109 155 203  29 139 103 204 185  33 221  73 233  18 253  65 161 182 241 144 176 117 194 128 235  71   8 249 122  73   6 196  80 119  59
			 215 138 112 233  66   0  96 171  79 213 119  43 229   3  96  41 114 236  30 128 231  88 155 198 104 230 152  76 137 254  48  16  75 247 180  20  69 230 106 154 199  42 167 115 196  99 130  50  12  93  21  51 146  27 162 199  85 152 212 105 178  37 203   9
			  72  35  13  50 188 222 149  20  51 153 238 170 194  56 219 181 135  65 197 170 211  38 183  63   9  88 208 182  12  91 175 197 125  90 214  43 124   2 141  54 130 182  89  53   2 227  74 199 233  67 184 239 102 216  19  48 230 135  30 235 128 143 245 102
			 154 236 200 141  77 117  24 248 187 108  66  18 101 152  21  78 210   5 104  79 137  14 117 240  29 164 112  42 123 226  60 146  36   9 109 159 241  84 174 249  98  23 236 210 127  25 156 116 147  34 208 160  72 136 183 113  64 172  96  60 165  85  49 184
			  24  86 169 104 242 176 131  89 218 138  34 206  74 227  31 160 244  43 149 253  53 226  73 145 213 129 245  69 216 158 102 242 206 171 225  61 188  27 215  67 204  34 151  72 169 246 190  83 218 131 105   5  42 247  87 219   1 194 254  12 213  20 229 114
			 194  56 223  38  16 212  49 161  71   9 174 250 111 139 189  92 118 177  17 192 163  97 200 177  84  56 174 141 193  26   0  73 134  52  82  19 145  95  13 162 120   7 191 108  17  57  99  11  46 253 174  80 202 125 168  35 154 126  47 116 176  72 158  28
			 251   2 123 160  64  95 191 114 239 197  55 154  15  48 236  23  56 223  76  25 115  19  40 120   3 222 102  15  79 117 231 165 110 192 252 118 202 237 111  43 231  83 243  42 221 181 124 205 157  61  23 224 151  58 232 101  70 204  84 227  37 105 207 140
			  98 180  78 205 139 250   5 147  37  97 131  81 215 170  69 207 158 102 201 132 238 210  64 249 159  34 197  52 251 146 187  44 219  13  32 158  49  71 171 194 142  55 159 132  89 144  32 232  78 192  98  29 113 196 139  15 245 171 143 130 186 243  18  67
			 218  36 233 109 173  31  80 229 126 208 179 233  27 100  11 121  35 241 146  55  81 167 139 187  91 232 152 129 214  95  63 131  89 151 102 182 214 137  16  91 223 121 185 211  65 248 166 107   0 136 235 177  10  83  47 185 112  25 216  61   4  86  51 169
			 132 153  11  52 128 216 184  60 165  45   2 110 140 201 247 177  81   0 118 185 229   8 105  48  17  70 108 177  38   9 205 172 244  68 232   3  85 246  35 208  66   2  28 100  11 198 129  58 220  40 159  68 249 214 163 226  66  24  95 164 234 146 203 115
			  85 193  70 242  88 151 108  13 221  79 254  58 160  77  49 149 219 193  43 159  94  33 194 240 145 211  24  61 226 158 107  29  22 188  43 122  61 178 128 156 107 251 167 230 118  41  83 177 144  89 202  21 119  35  97   3 152 242 201  43 106 179  32 247
			  50 226 164 139 202  43 246 135 100 150 184 122 226 190 129 113  60  99 251  71 140 221 121  77 172  27 248 192  87 140 235  77 215 138 165 225 149  97 233  51 189 146  85  61 183 154 238 208  15 245 108  54 148 205 133  51 191  79 123  12 224  75 129   6
			 110  21  26 100 124 187  64 168  29 200  18  40  89   8  33 238 169 135  13 204 179  17  53 205   3  94 162 119  17  43 184   5 111  53  92 202  25   8 196  77 122  41 203  18 220 135  56 111  26  72 164 187 232  85 180 236 105  36 176 154  54 140 213 185
			 150 208 172 237  76  18 215  92 237  69 108 241 172 214 145 197  84 213  28 109  60 245 157 105 234 138  51  74 239 210  61 160 247 191  13  74 254 105 164 220  15 240 138 109  33  94   4 170 195 224 133  39   6  66 157 124 218  22 250  89 193 239  96  66
			 253  88  55   2 221  39 145 180   5 126 207 149  54 103  71  18  50 155 237 172 131  92  34 180  67 198 220 175 148  97 134  86  34 146 219 118 182  62 136  35  94 173  72 231 156 204 252  81 148  18  91 216 113 254  29  14  76  56 208 115  29  24 167  39
			 188 121 139 182 103 162 116  56 220  40 166  80 131 224 178 249 126  98   4  78 192 144 226 122  23  41  15 109  31  11 198 228 174 101 130  40 157  22 238 200 149  56 189  12  48 181  64 122  44 239  58 174 143 193  99 171 197 138 165   5  73 124 222   9
			  74 217  35 242  67 204 252  86 141 191  98 247  25   5 114  38 187 222  57 212  42  18 201  80 239 153  88 249 184 217  47 127  69 238  56 202 232  85  51 116   1 250 103 210  85 141  22 222 183 105 205 125  78  46 219 119 232  39  97 238 183 204  53 105
			  22 170 151  90  15 135  29 127 234  63  12 212 143 200  64 158  83 129 168 114 254 160  52 107 172 195 136  54 157  77 103 166   1 187 140  95   8 193 169 219  80 161  27 125 164 243  34  96   6 156  31  17 237 158   1  54  85 152 212  60 132  92 144 244
			 198  57 114 220 197  58 184 157 108 176 120  51 164  93 240 138 231 202  32  14  94  68 222   1  25  65 224   8 118 232 138 252  27 116 212  72 146  30 107 137  45 213 142 233  59 110 178 207  71 249 190  65 209  93 135 186 248  12 113 175  42 227 158  30
			  87 237   6  42 165  98 229  69 209  36 137 228  74 189 127  46 106  63 150 236 176 133 190 121 244 129  83 209  35 175  57 192  82 158  47 245 179 223  65 244 184 117  70 176   4 216 133  52 128  90 144 107 168  36 225  69 161  26 142 243  80   1 181 119
			  19 173  73 139 248 125   0 145  90 250 185 101   9  33 217 174   4 190 125  79 205  36 152  75 206 166 110 186 147  93  10 214  20 226 131 102  14 120 162   6  89  21 204  98  44  80 153 235 170 201  47   8 244 118 197  19 104 207  62 128 194 107  66 211
			  47 229 107 187  82  36 195  48 165  14  59 153 243 117 136  78 251  96 220  50   8 112 231  98  53 143  43 228  62 239 124  43 110 172  59 198  39  79 202  50 228  33 242 138 192 253 102  10  25 114 231 182  58  85 142  49 180 231  93 167 223  35 252 137
			 192 152  24 216 157 224 104 237 122 217  83 201  44 165 199  58 154  27 166 137 246  62 178  14 191 252   5 101  24 181 160  71 244 144  86 230 149 253 131 101 173 120  59 165  24  37 183  68 209 135  75 152 126 206 166 253  77   6 148  50 118  12 159  95
			 116  70  18 120  58  10 135  75 176  27 111  23 224  89 108 233  17 208 114 187  93 157 216  30 115  71 160 214  82  29 206  98 191  33 183  21 105 166  63 220 144 198   8  75 223 146 119 229 159  93 219  38 237  12  30 111 133  38 214 186  84 203  61 235
			   3 211 170 238  94 181 206  54 148 244 191 141  68   6 181  47 134  86  60 223  40  17  78 141 234 131  39 195 145 248  16 136 224   7 122  73 205  26 190  18  40  86 235 106 202  54  88  16  46 189   2 174 101  68 221 193 160 239 104  17 246 141 174  39
			 156  87  48 197 130  33 160 227  99   4  47 161 254  32 218 151 196 248   0 151 126 242 166 207  95 176 225 121  54 112  64 157  45  93 214  53 241   0 116  73 247 180 154  28  20 176 239 198 130 250  56 118 142 182  89 127  55  81 176  67  29 126  78 225
			 133 246 109 147  68 250  88  22 123 211  78  97 176 131 113  74 100  37 170  82 201  67 109  49   3  60  85  14 170 190 234  83 179 249 132 165 148  88 227 168 133 114  61 218 122  70 154  33 104 145  83 216 241  49 152 235   0 208 138 229 156 213  99 187
			  66  30 181   6 213 116 189  41  63 183 235  13 204  51 237  10 179 217 117 230  29 179 138 190 250 152 199 242  97  38   2 207 128  62 107 198  37 125 202  47  93 208   4 187 249  97   7 217  65 184 163  28   9 132 204  35 116 166  43 111 196   9  48 120
			 200  19 222  80  46 156  14 232 168 139  33 111  68 142 194 159  64 132  52  22  92  10 228  39 101 125  26  73 160 221 149 102  29 170 236  80  11 178  65 150 240  36 144  79 161  41 173 119 234  13 207 110 188  93  70 177  96 250  15  61  87 245 140 229
			 162 100 138 168 240 101 203  74  95 128 215 156 246  20  91  25 210 245 148 195 242 112 154  80 219 182 140 210 115  20  59 188 228 117 142  51 218 252 112 128 185 104 233  53 133 229 195  88  46 129  77  57 245 161 227 128 213  76 189 125 168  36 178  76
			  53 254  39 197  61 134  26 150 252 192  57  87 171  44 227 108  16  75 101 165  64  44 203 128 165  55   7 237  46  87 253 138  74   6 193 156  99 135  28 205  71 171  13 209 110  19  63 140 254 158 225 144 127  36 111  55 147  25 155 227 134 207 106   4
			 212 129  90 116  11 182 229   1  45 116  19 222 121 203 144 183 124 175  35   3 220 180 120  69 233 109  90 190 164 124 178  42 212  92  35 209  62 166  84 231 126  45 153  89 189  26 214 169 100  34 184  90 217   6 196 131 233 102 202  50  95  67 239 151
			  80 186 225 153 210  81 107 174 214  79 182  31   5  77  61 253  50 206 239 143  89 130 247  30 138 208  39 130  70 203  11 108 162 246 127  22 226 187   2 145  95 215 251  66 139 242  81   5 198  24 117  50 173  66 252  84 172   3 119 248  12 183 118  28
			 169  17  66  35 248  51 147  63 129 161 240 107 230 191  99 157   9  84 115 193  48 160  79 191  15 174 248 150 225  30 238  67 141  53 174  76 116  39 247  52 195  10  35 179  16 162 119  53 222  71 245 208 134 100 156  41 191  59  79 144  38 159 224 132
			  51 241 109 173 136 122 188 243  98  40 142  58 165 127 134  34 222 167  62  17 229 107 213 147  97  58  81   0 113  93  23 181 221  98 204 239  14 102 156  78 168 106 123 225  95  43 234 187 148  96   9 153  28 228 120 217 135 237 164 212 193  62  87 201
			  99 147 207   7  93 200  32  11 225 201  16  91 212  45 238 194 109 133 210  28 171  65   5  38 221 160 200  46 188 215 155  42 122   4  24 151  58 196 216  24 238  63 207 155  72 200 106 135  32 178  59 195  83 180   8  73 109  31  14  92  23 113 233   0
			 190  41  76 234  54 221 157  85 137  68 185 251 146  74 173  90  54 244  75 148 237 122 183 250 114  20 240 126 170  57  83 249 192  71 171 133 231  88 126  30 186 141  48 131 241   0 172  79 229 123 240 112  19 243  51 206 149 185 222  48 246 140  34 157
			 252  21 120 181 142  72 115 180  45 163 111  27   1 119 209  17 151 182   4  98 198  86  52 143  67  89  26 145 100 226   9 146 111 228  94 189 117  45 177   8  74 223  90 189  28 121  60 204  11 161  45 212  69 124 162  96 249  66 123 170  73 178 205  63
			  84 168 220  25 103 249   3 210 241  20 206  83 155 226  62 112  32 220 124  41  22 158 206  11 217 177 231 195  72 137  34 202  54  15  41 254  75 219 144 244 113 163  19 104 215 159 248  40 104 221  88 145 173  36 198 139  42   2 102 150 218  97  10 116
			 214  51 149  15 198 161  37  64  92 133  53 237 190  41 168 247 195  81 166 254  69 225  32 100 163 122  57 108  14 238 179  86 165 215 153 125   2 163  99  52 203  38 252 146  69  16  86 184  21  63 130 190  99 222  22  82 171 228 192  27  20  52 238 137
			 187  94 243  62  88 231 120 195 150 222 175  12 101 140  90   7 134  50 104 204 139 112 180 245  46  18 212 153  42 206 115  21 245 102  68 180  33 210  67 187  13  82 179  51 198 228 114 150 236 200  25 253   4  57 237 110 208  74 131 244  82 180 155  32
			 110   5 206 115  24  52 175  16 107  32  76 122  60 205 233  72 157 236  14 183  56   1  83 147  73 188  88 253 170  59 150  76  28 138 198 236 109  23 241 124 153 234 118   5  97  33 174  49  78 142 108 162  80 141 180  31  13  55 162 100 199 121 230  75
			 140 171  38 159 191 139 216  84 254 199 158 242 182  19  30 176 113 211  91  25 162 241 202 121 233 132  31  10 124  99 235 184 208  18  55  88 148  46 171  92  26 212  64 223 167 135 246 123 215 179  17 220  44 201 120 154 250 139 225  44  10  61  22 209
			 240  65 224  81 247  29  70 161  48   7 134  41 110 219 144 200  64  44 147 227 101 132  38  59 169 102 223 194  72 218   1  49 112 229 173  10 192 221  75 200 142 106 159 130  76 205  60   2  97  37  69 189 100 230  65  94 188  77 114 175 218 103 158  47
			 181 125  17 148 106   2 236 118 184  98 227  81 164  53  97   9 123 248  23 197  65 185 220   9 199 155  50 142 175  37 133 166  85 151  36 242  61 112  21 251  11  52 196  39 232 108 151 195 230 136 243 126   8 161  22 212  39   4 203 143  33 249 193  88
			  27  98 200  45 211 171  90  22 205  62 144 211 125 251  77 222 184 163  82 114  16 151  92 117  70 247  86 117 240  92 203 250  58 218 123  98 162 136  40 166  69 182 244  93   9 185  28  82 169  54 156  83  30 247  52 167 105 240  57  90 169  68   1 134
			 209 253 165  76 123  59 221  43 130 234  26 188   0 177 148  34 103  56 235  36 223  49 243 177  28  15 131 209  63  12 149 105  23 194   5  77 209 186 233  96 217 115  24 154  57 122 254  15 114 209 103 200 177 143  86 224 124 179 130 226  19 119 232 153
			 115  67   8 193 234  15 180 149  79 165 114  91  66  44 235  16 214 152   3 181 137 164  75 203 143 220 173  42 159 195  25  76 176  44 143 247  29 127  59   0 146  32  82 206 167 217  72 147 223  40  22 234  62 113 191  11  70  26 150 189  43 199  81  53
			 185 136  38 104 147  31 100 250 193  14 242 204  23 118 192  79 133 198  92  68 210 103   6 121  55 102  73 231 110 132 235 211 117 228  63 167 108 151  82 200 228 179 136 241  44  20 100 178  59 188  78 121   0 221  37 155 253 210  99  62 245 107 161 217
			 127 226 158 242  82 218 134  66  40 104  52 153 225 164 101  51 243  28 119 253  19  34 225 179 249 155 197   3  87 182  60  11 151  95 199  14 213 237 173  45 106  60  13  73 110 195  34 241   6 140 250 163  50  96 204 133  84  17 120 168   7 137  31  96
			  48  85 180  57  21 169 201   3 215 142 183  77  32 135 207 175  20 154 172  55 188 145  84  46  92 128  33 141 246  41 167  81 252  35 135  74  49  93 136  17 252 154 216 182 149 232 132  86 160 106  27 196 228 128 167  60 185  47 237 193  77 219 177 241
			 152 208   5 119 191  42 113  81 166 232 123   6 253  90  63 227 106  70 231 132  99 238 169 205  10 186 221  63 201  20 108 207 126 190 170 230 120 186  35 196  76 121  25  93   7  49 168 219  68 206  13  90 144  71 244 110 216 156  94  37 145  56 118  16
			  68 108  25 251  76 226 153 246  28  94  56 213 188  21 148  40   6 215  87 202  44 123  65 134 234  74 115 173  91 154 236  48   1  59 105 155   7 245 148 102 224 164 190 243  65 201 115  22  41 236 174 118  42 186   7  30 127  11 223 129 202 251  88 195
			 238 175 215 149 129  97  54 133 194  18 111 163  45 103 233 197 162 120  34 150   0 217 159  26  99 164  50  12 227  29 133 178  78 242 210  27  86  67 209  50   3  58 137 105 129 230  77 189 101 134  58 246 156 211  87 228 174  72  53 179 107   2 169  39
			 136  91  19  62 200 166  13 178  67 207 148 244  75 177 130  84  58 186 249 172 106  80 245  14 197 143 254 127 194  70 103 223 150  94  16 179 225 128 168 113 239  87 218  41 175 150  30   1 226 154 193  78  19 106  57 145 102 203 243 149  28  74 211  24
			 221 162  46 112 234  34 217 105 240  86  37 126   8 219  25 242 140  96  15  67 197  49 181 114  59 212  37  85 170 147 206 124  36 196 132  49 115 195  37 140 183 155 194  10 248  89 216 169  52  87 125  31 220 170 196 252  38  16 122  93 229 158 117  53
		</levels>
	</threshold>
	<threshold map="bni64x64">
		<description>Bluenoise dither map inverse 64x64</description>
		<levels width="64" height="64" divisor="256">
			  68 175  10 254  74 166 118 210 250  88  33  72 196 139 100 243  45 209  31 119  20 236 109  28 164  80 253 145  16 212 248 192   4  94 182  19 112 165   0 185 128 224 177 140 194 232 117 151   2  56 246  21 119 209 251 137 171  87  65 193 242  72  20 155
			 114 225  61 130 184  99  67  25 128 199 154 118  46 164  64 190  82 139  96 226 163  88 216 184 234 132  24 200 118  40 164  69 232 146  38  84 193 128  39 154  56 123  19  47  83 211  69 187 110 215 144  77 161  97 181  42 102  21 211  36 113 218 185 248
			  46 149  28 109 206   1 144 186 102  63   5 224  94  24 213 149   1 176  54 127  41 143   4  71  38 225  56  94 183  78 138  27 209 168 245 224  67 103 209  84  30 199 105 163 130  15  43 243  31  88 184  46 200  15  70 231 235 187 146 126  51 160   3  80
			 237 189  86 164 125  56 228 234  42 175 139 254 185 130 233  48 109 252 200  70 191 248 171 123  99 151 173 232   6 244 231  98 112  48 129  12 151  50 255 136 174 240  69 219 251 179 145 228 161 128  11 239 108 131 152  25 114  79   7 177  88 132 104 210